# OpenAPI spec output location (optional, defaults to tools/codegen/openapi.json)
openapi_output: tools/codegen/openapi.json

# Path to the Python package repository (required)
# This is used both as the output directory for generated Python code
# and as the repository path for updating pyproject.toml
repo_path: /Users/andrewtruong/repos/weave-stainless

# Optional output paths for other languages
# node_output: weave-node
# typescript_output: weave-typescript

# Package name for pyproject.toml updates (required)
package_name: weave_trace

# Whether to use release version instead of git SHA (optional, defaults to false)
release: false
